###########################
######### 生产模式
##########################
spring:
  # 环境 dev|test|prod
  profiles:
    active: prod

#########################
######## mybatis
#########################
mybatis:
  type-aliases-package: com.qiang.modules.sys.pojo
  mapper-locations: classpath:mapping/*Mapper.xml









